"""
Network Intrusion Detection — Interactive Dashboard
Run with: streamlit run dashboard.py
Expects a data/ subfolder (next to this file) containing the CSVs generated by notebooks 1-5.
"""
import streamlit as st
import pandas as pd

DATA_DIR = "data/"

st.set_page_config(page_title="Intrusion Detection Dashboard", layout="wide")

st.title("Network Intrusion Detection — Model Dashboard")
st.caption("Real NSL-KDD benchmark dataset (Tavallaee et al., 2009)")

# ---------- Load data ----------
try:
    model_comparison = pd.read_csv(DATA_DIR + "model_comparison.csv")
    confusion = pd.read_csv(DATA_DIR + "confusion_matrix.csv", index_col=0)
    preds = pd.read_csv(DATA_DIR + "test_predictions.csv")
    feature_importance = pd.read_csv(DATA_DIR + "feature_importance.csv")
except FileNotFoundError as e:
    st.error(
        f"Missing file: {e.filename}. Make sure the data/ folder sits next to dashboard.py "
        "and contains the CSVs generated by notebooks 01 through 04 (run them in order first)."
    )
    st.stop()

# Extension results are optional (only exist if notebook 5 was run)
try:
    extended = pd.read_csv(DATA_DIR + "final_model_comparison_with_extensions.csv")
    # notebook 5 names this column "novel_detection_rate" (no "attack") -
    # rename so it matches model_comparison.csv's "novel_attack_detection_rate"
    extended = extended.rename(columns={"novel_detection_rate": "novel_attack_detection_rate"})
except FileNotFoundError:
    extended = None

# ---------- KPI row ----------
best_row = model_comparison.loc[model_comparison["macro_f1"].idxmax()]

c1, c2, c3, c4 = st.columns(4)
c1.metric("Best Model", best_row["model"])
c2.metric("Best Macro F1", f"{best_row['macro_f1']:.3f}")
c3.metric("Novel-Attack Detection", f"{best_row['novel_attack_detection_rate']:.1%}")
c4.metric("Total Test Records", f"{len(preds):,}")

st.divider()

# ---------- Model comparison ----------
st.subheader("Model Comparison")
chart_source = extended if extended is not None else model_comparison
st.bar_chart(chart_source.set_index("model")[["macro_f1", "novel_attack_detection_rate"]])

if extended is not None:
    st.caption("Includes XGBoost and SMOTE extension results (notebook 5).")

st.dataframe(chart_source, use_container_width=True)

st.divider()

# ---------- Confusion matrix ----------
st.subheader("Confusion Matrix — Best Model (Logistic Regression)")
st.caption("Rows = actual attack type, Columns = predicted attack type. Diagonal = correct predictions.")
st.dataframe(confusion.style.background_gradient(cmap="Blues"), use_container_width=True)

st.divider()

# ---------- Feature importance ----------
st.subheader("Top Predictive Features")
st.caption("From Random Forest, used here for interpretability alongside the deployed Logistic Regression model.")
top_features = feature_importance.head(15).set_index("feature")
st.bar_chart(top_features["importance"])

st.divider()

# ---------- Novel attack breakdown (interactive) ----------
st.subheader("Novel Attack Type Detection")
st.caption("Attack types that never appeared during training — the true test of generalization.")

novel = preds[preds["is_novel_attack_type"] == 1]
novel_summary = novel.groupby("label").agg(
    occurrences=("label", "size"),
    detected=("predicted_category", lambda x: (x != "normal").sum())
).reset_index()
novel_summary["detection_rate"] = (novel_summary["detected"] / novel_summary["occurrences"]).round(2)
novel_summary = novel_summary.sort_values("occurrences", ascending=False)

min_occurrences = st.slider(
    "Minimum occurrences to show", 1, int(novel_summary["occurrences"].max()), 1
)
filtered_novel = novel_summary[novel_summary["occurrences"] >= min_occurrences]
st.dataframe(filtered_novel, use_container_width=True)

st.divider()

# ---------- Prediction explorer ----------
st.subheader("Explore Predictions")
category_filter = st.selectbox(
    "Filter by actual attack category",
    ["All"] + sorted(preds["attack_category"].unique())
)

view = preds if category_filter == "All" else preds[preds["attack_category"] == category_filter]
st.write(f"Showing {len(view):,} of {len(preds):,} records")
st.dataframe(view.head(200), use_container_width=True)

st.divider()
st.caption(
    "Dataset: NSL-KDD. Best model: Logistic Regression, chosen for its stronger generalization "
    "to novel attack types over more complex alternatives (Random Forest, XGBoost)."
)
